### ISSUE TITLE
Recommendation Algorithm/Implementation

### ISSUE THREAD

**Issue by abhinavtripathy** [IMDB-2-0/CS497-B#7]

**Comment by hansquiogue** [comment]
Current issues:
- Long response time to retrieve recommendations
  - Perhaps chunk or set some limit to number of user ratings to fit and number of movie recommendations to respond with
- Memory related issues with Docker and PySpark
  - Need to assign more memory to Docker container and update PySpark memory usage (it's too low)

TODO:
- ~~Obtain best ALS model and tune hyperparameters through cross validation~~
- ~~(Optional): utilize 1B dataset~~
- ~~(Optional): use Spark Streaming for real time data processing~~

**Comment by hansquiogue** [comment]
Updates:
- Memory issues slightly fixed by increasing Spark driver and executor, and Docker Engine memory
- Best ALS Model hyperparameters with lowest ROEM (out of 192 models and 5 folds):
  - Rank: 50
  - Max iterations: 10
  - RegParam: 0.1  
- ALS Model can be refitted with new training data (new users) by simply running `retrainALSModel.py`

TODO: 
- ~~Limit long response time by making recommendations for each user persistent~~
- ~~Link recommender system API with dashboard~~
